### ISSUE TITLE
v1.006 Interpolation issue - uni049D.sc

### ISSUE THREAD

**Issue by kenmcd** [tphinney/science-gothic#291]
Sorry, found one more while checking the previous issues.
File: ScienceGothic[YOPQ,slnt,wdth,wght].ttf  - v1.006 (2022-04-14)
Glyph: uni049D.sc

![2022-04-15_11-07-20](https://user-images.githubusercontent.com/844920/163606073-eb6edbf7-4c1c-4eca-979f-fd5cd431ab33.gif)

**Comment by tphinney** [comment]
Ouch, that is not even just a start point moving, but a bad outline for the :Black master.
I have fixed it in the VFC source, so it should be in the next build.

**Comment by kenmcd** [comment]
Unfortunately there still appears to be an issue.
This is from the updated VFC (ScienceGothic[YOPQ,slnt,wdth,wght].vfc)

![2022-04-15_17-06-09](https://user-images.githubusercontent.com/844920/163653987-f5347238-46ab-4ac0-910d-a3b1dfab315a.gif)

**Comment by tphinney** [comment]
D'oh! Quite right. I should have realized that if the Blk Ctr master was messed up, the Blk Ctr S (slanted) master likely was as well.

Anyway, this is now even more fixed in source, for the next build.

**Comment by kenmcd** [comment]
All appears to be working now in VFC posted today (2022-04-19).
Closing.
